### ISSUE TITLE
Upload recorded videos to S3

### ISSUE THREAD

**Issue by okaycj** [lookit/ember-lookit-frameplayer#308]
# Summary 
Currently, [Pip](www.addpipe.com) handles uploading video files to our S3 store.  As we're replacing Pipe, this functionality will need to be replaced using the [AWS S3 Javascript SDK](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html). 

# Implementation
The S3 documentation recommends using the SDK over wrapping the REST API.   Additionally, using S3's multipart upload has it's benefits and draw backs.  The most notable draw back is that if we don't stop/abort an upload, we're charged for storing the parts of the upload, seemingly, indefinitely.  

S3 might have a ["timeout" setting](https://stackoverflow.com/a/39712169) that we could use to remove "abandoned" multipart uploads.

# AC

- [x] Replace upload placeholder with upload to S3
- [x] Use S3's [multipart upload](https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpuoverview.html)
- [x] ~~Attempt to abort upload when browser is closed before end of experiment~~ (BG created separate issue: #348)
- [x] ~~Script to check if there are uploads and determine if an upload has been "abandoned"~~ (BG crossed off as being out of scope for this EFP issue)

**Comment by mekline** [comment]
This got moved into the "Done" column - is it actually done or still pending finishing the rest of the video upload pipeline?

**Comment by becky-gilbert** [comment]
I think we're done with the majority of this issue, which is the implementation and integration of the S3 class and successful uploading (i.e first two items acceptance criteria checklist). But I would like to leave this issue open because we still need to look at the last two items in the checklist. 

Also, a question about this item:
> Attempt to abort upload when browser is closed before end of experiment

When the browser tab/window is closed early, do we want to abort the upload or quickly try to complete it? Does that depend on whether there are any upload parts that are still in progress?

**Comment by becky-gilbert** [comment]
Status update: 
I would like to keep this issue open so that we can address this task from the AC checklist at some point in the future. 
> Attempt to abort upload when browser is closed before end of experiment

I think the task below is also important but probably won't entail changes in the EFP repo, so I've crossed it off the AC list above (I don't know whether this script should be part of the lookit-api or elsewhere?)
> Script to check if there are uploads and determine if an upload has been "abandoned"

Note: there are some remaining problems getting the actual S3 uploads to work on staging/production because of problems with the environment variables. But those problems are not in the scope of this EFP issue as they are addressed in separate issues:
https://github.com/lookit/lookit-api/issues/1074
https://github.com/lookit/lookit-orchestrator/issues/36
